### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by nichoth** [substack/node-trumpet#60]
Using with http:

```js
var http = require('http');
var trumpet = require('../');
var tr = trumpet();

http.createServer(function(req, resp) {

  tr.pipe(resp);

  var ws = tr.select('tbody').createWriteStream();
  ws.end('<tr><td>rawr</td></tr>');

  var fs = require('fs');
  fs.createReadStream(__dirname + '/html/table.html').pipe(tr);

}).listen(8000);
```

Produces error:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (/Users/nick/code/nodes/substack/node-trumpet/node_modules/readable-stream/lib/_stream_writable.js:161:12)
    at Trumpet.Writable.write (/Users/nick/code/nodes/substack/node-trumpet/node_modules/readable-stream/lib/_stream_writable.js:208:5)
    at ReadStream.ondata (_stream_readable.js:540:20)
    at ReadStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at ReadStream.Readable.push (_stream_readable.js:126:10)
    at onread (fs.js:1683:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:529:17)
```

**Comment by rainydio** [comment]
You need to create new instance of `tr` for every request.

```js
var http = require('http');
var trumpet = require('trumpet');

http.createServer(function(req, resp) {
  var tr = trumpet();
  tr.pipe(resp);

  var ws = tr.select('tbody').createWriteStream();
  ws.end('<tr><td>rawr</td></tr>');

  var fs = require('fs');
  fs.createReadStream(__dirname + '/html/table.html').pipe(tr);

}).listen(8000);
```

**Comment by nichoth** [comment]
Thanks @rainydio
